version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports: 
    - '3000:3000'
    volumes: 
    - .:/usr/src/app
  articles:
    container_name: articles
    build:
      context: .
      dockerfile: ./apps/articles/Dockerfile
      target: development
    command: pnpm run start:dev articles
    env_file:
      - ./apps/articles/.env
    ports: 
    - '3001:3001'
    volumes: 
    - .:/usr/src/app
  static:
    container_name: static
    build:
      context: .
      dockerfile: ./apps/static/Dockerfile
      target: development
    command: pnpm run start:dev static
    env_file:
      - ./apps/static/.env
    ports: 
    - '3002:3002'
    volumes:
      - .:/usr/src/app
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports: 
    - '3003:3003'
    volumes:
      - .:/usr/src/app
  comments:
    container_name: comments
    build:
      context: .
      dockerfile: ./apps/comments/Dockerfile
      target: development
    command: pnpm run start:dev comments
    env_file:
      - ./apps/comments/.env
    ports: 
    - '3004:3004'
    volumes: 
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb1
    ports:
      - '27017:27017'
    networks:
      - my_network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: mydb1
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - '8081:8081'
    restart: always
    networks:
      - my_network
    depends_on:
      - mongo

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports: 
    - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: password
      POSTGRES_PASSWORD: mydb1
      PGDATA: '/var/lib/postgresql/data/pgdata'

  rabbitmq:
    image: rabbitmq
    ports:
      - '8000:8000'
